In [3]:
import numpy as np
Q = np.arange(30).reshape(5,6)
print(Q)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [4]:
Q[2,4]

np.int64(16)

In [11]:
Q[:,4]

array([ 4, 10, 16, 22, 28])

In [14]:
sub = Q[1:4,2:5]
sub

array([[ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])

In [15]:
Q[1:4, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])